//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws2.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebS1Soap")]
    public interface WebS1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ws2.ServiceReference.HelloWorldResponse HelloWorld(ws2.ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ws2.ServiceReference.HelloWorldResponse> HelloWorldAsync(ws2.ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name obtainDateResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtainDate", ReplyAction="*")]
        ws2.ServiceReference.obtainDateResponse obtainDate(ws2.ServiceReference.obtainDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtainDate", ReplyAction="*")]
        System.Threading.Tasks.Task<ws2.ServiceReference.obtainDateResponse> obtainDateAsync(ws2.ServiceReference.obtainDateRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saludo", ReplyAction="*")]
        ws2.ServiceReference.saludoResponse saludo(ws2.ServiceReference.saludoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saludo", ReplyAction="*")]
        System.Threading.Tasks.Task<ws2.ServiceReference.saludoResponse> saludoAsync(ws2.ServiceReference.saludoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ws2.ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ws2.ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ws2.ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ws2.ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtainDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtainDate", Namespace="http://tempuri.org/", Order=0)]
        public ws2.ServiceReference.obtainDateRequestBody Body;
        
        public obtainDateRequest() {
        }
        
        public obtainDateRequest(ws2.ServiceReference.obtainDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class obtainDateRequestBody {
        
        public obtainDateRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtainDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtainDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public ws2.ServiceReference.obtainDateResponseBody Body;
        
        public obtainDateResponse() {
        }
        
        public obtainDateResponse(ws2.ServiceReference.obtainDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtainDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtainDateResult;
        
        public obtainDateResponseBody() {
        }
        
        public obtainDateResponseBody(string obtainDateResult) {
            this.obtainDateResult = obtainDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saludoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saludo", Namespace="http://tempuri.org/", Order=0)]
        public ws2.ServiceReference.saludoRequestBody Body;
        
        public saludoRequest() {
        }
        
        public saludoRequest(ws2.ServiceReference.saludoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class saludoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public saludoRequestBody() {
        }
        
        public saludoRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saludoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saludoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ws2.ServiceReference.saludoResponseBody Body;
        
        public saludoResponse() {
        }
        
        public saludoResponse(ws2.ServiceReference.saludoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class saludoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string saludoResult;
        
        public saludoResponseBody() {
        }
        
        public saludoResponseBody(string saludoResult) {
            this.saludoResult = saludoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebS1SoapChannel : ws2.ServiceReference.WebS1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebS1SoapClient : System.ServiceModel.ClientBase<ws2.ServiceReference.WebS1Soap>, ws2.ServiceReference.WebS1Soap {
        
        public WebS1SoapClient() {
        }
        
        public WebS1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebS1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebS1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebS1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ws2.ServiceReference.HelloWorldResponse ws2.ServiceReference.WebS1Soap.HelloWorld(ws2.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ws2.ServiceReference.HelloWorldRequest inValue = new ws2.ServiceReference.HelloWorldRequest();
            inValue.Body = new ws2.ServiceReference.HelloWorldRequestBody();
            ws2.ServiceReference.HelloWorldResponse retVal = ((ws2.ServiceReference.WebS1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ws2.ServiceReference.HelloWorldResponse> ws2.ServiceReference.WebS1Soap.HelloWorldAsync(ws2.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ws2.ServiceReference.HelloWorldResponse> HelloWorldAsync() {
            ws2.ServiceReference.HelloWorldRequest inValue = new ws2.ServiceReference.HelloWorldRequest();
            inValue.Body = new ws2.ServiceReference.HelloWorldRequestBody();
            return ((ws2.ServiceReference.WebS1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ws2.ServiceReference.obtainDateResponse ws2.ServiceReference.WebS1Soap.obtainDate(ws2.ServiceReference.obtainDateRequest request) {
            return base.Channel.obtainDate(request);
        }
        
        public string obtainDate() {
            ws2.ServiceReference.obtainDateRequest inValue = new ws2.ServiceReference.obtainDateRequest();
            inValue.Body = new ws2.ServiceReference.obtainDateRequestBody();
            ws2.ServiceReference.obtainDateResponse retVal = ((ws2.ServiceReference.WebS1Soap)(this)).obtainDate(inValue);
            return retVal.Body.obtainDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ws2.ServiceReference.obtainDateResponse> ws2.ServiceReference.WebS1Soap.obtainDateAsync(ws2.ServiceReference.obtainDateRequest request) {
            return base.Channel.obtainDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ws2.ServiceReference.obtainDateResponse> obtainDateAsync() {
            ws2.ServiceReference.obtainDateRequest inValue = new ws2.ServiceReference.obtainDateRequest();
            inValue.Body = new ws2.ServiceReference.obtainDateRequestBody();
            return ((ws2.ServiceReference.WebS1Soap)(this)).obtainDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ws2.ServiceReference.saludoResponse ws2.ServiceReference.WebS1Soap.saludo(ws2.ServiceReference.saludoRequest request) {
            return base.Channel.saludo(request);
        }
        
        public string saludo(string name) {
            ws2.ServiceReference.saludoRequest inValue = new ws2.ServiceReference.saludoRequest();
            inValue.Body = new ws2.ServiceReference.saludoRequestBody();
            inValue.Body.name = name;
            ws2.ServiceReference.saludoResponse retVal = ((ws2.ServiceReference.WebS1Soap)(this)).saludo(inValue);
            return retVal.Body.saludoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ws2.ServiceReference.saludoResponse> ws2.ServiceReference.WebS1Soap.saludoAsync(ws2.ServiceReference.saludoRequest request) {
            return base.Channel.saludoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ws2.ServiceReference.saludoResponse> saludoAsync(string name) {
            ws2.ServiceReference.saludoRequest inValue = new ws2.ServiceReference.saludoRequest();
            inValue.Body = new ws2.ServiceReference.saludoRequestBody();
            inValue.Body.name = name;
            return ((ws2.ServiceReference.WebS1Soap)(this)).saludoAsync(inValue);
        }
    }
}
